-----------------------------------------
-- ALL NON DEFAULT INDICES IN DATABASE --
-----------------------------------------

-- BRANCH TABLE --
create index IDX_BR_PROJECT_ID on BRANCH(PROJECT_ID);
create index IDX_BR_TEMPLATE_ID on BRANCH(TEMPLATE_ID);

-- BRANCH_CISERVER TABLE --
create index IDX_BRC_BRANCHES_ID on BRANCH_CISERVER(BRANCHES_ID);
create index IDX_BRC_CISERVERS_ID on BRANCH_CISERVER(CISERVERS_ID);

-- BRANCH_VERIFICATION_CONF TABLE --
create index IDX_BRVC_VERIFICATION_ID on BRANCH_VERIFICATION_CONF(VERIFICATION_ID);
create index IDX_BRVC_BRANCH_ID on BRANCH_VERIFICATION_CONF(BRANCH_ID);
create index IDX_BRVC_PRODUCT_ID on BRANCH_VERIFICATION_CONF(PRODUCT_ID);

-- BUILD TABLE --
create index IDX_B_BUILDGROUP_ID on BUILD(BUILDGROUP_ID);
create index IDX_B_STARTTIME on BUILD(STARTTIME);
create index IDX_B_ENDTIME on BUILD(ENDTIME);

-- BUILD_BUILD TABLE --
create index IDX_BB_CHILDBUILDS_ID on BUILD_BUILD(CHILDBUILDS_ID);
create index IDX_BB_PARENTBUILDS_ID on BUILD_BUILD(PARENTBUILDS_ID);

-- BUILD_CUSTOM_PARAMETER TABLE --
create index IDX_BCP_BUILDVER_CONF_ID on BUILD_CUSTOM_PARAMETER(BUILDVERIFICATIONCONF_ID);

-- BUILD_GROUP TABLE --
create index IDX_BG_JOB_ID on BUILD_GROUP(JOB_ID);
create index IDX_BG_STARTTIME on BUILD_GROUP(STARTTIME);
create index IDX_BG_ENDTIME on BUILD_GROUP(ENDTIME);
create index IDX_BG_PROJECT_ID on BUILD_GROUP(PROJECTID);

-- BUILD_EVENT TABLE --
create index IDX_BE_BUILD_ID on BUILD_EVENT(BUILD_ID);

-- BUILD_RESULT_DETAILS_PARAM TABLE --
create index IDX_BRDP_BVC_ID on BUILD_RESULT_DETAILS_PARAM(BUILDVERIFICATIONCONF_ID);

-- BUILD_FAILURE TABLE --
create index IDX_BF_BUILD_ID on BUILD_FAILURE(BUILD_ID);

-- BVC_TEST_RESULT_TYPES TABLE --
create index IDX_BTRT_BVC_ID on BVC_TEST_RESULT_TYPES(BVC_ID);

-- PROJECT_USER_ACCESS TABLE --
create index IDX_PUA_PA_ID on PROJECT_USER_ACCESS(PROJECTACCESS_ID);
create index IDX_PUA_UA_ID on PROJECT_USER_ACCESS(USERACCESS_ID);

-- PROJECT_ADMIN_ACCESS TABLE --
create index IDX_PAA_PA_ID on PROJECT_ADMIN_ACCESS(PROJECTADMINACCESS_ID);
create index IDX_PAA_AA_ID on PROJECT_ADMIN_ACCESS(ADMINACCESS_ID);

-- PROJECT_CHANGE_TRACKER TABLE --
create index IDX_PCT_PROJECT_ID on PROJECT_CHANGE_TRACKER(PROJECTS_ID);
create index IDX_PCT_CT_ID on PROJECT_CHANGE_TRACKER(CHANGETRACKERS_ID);

-- SYS_USER_IMAGE TABLE --
create index IDX_SUI_SYSUSER_ID on SYS_USER_IMAGE(SYSUSER_ID);

-- TEST_CASE_STAT TABLE --
create index IDX_TCS_BUILD_ID on TEST_CASE_STAT(BUILD_ID);
create index IDX_TCS_COMP_ID on TEST_CASE_STAT(COMPONENT_ID);

-- TEST_COVERAGE TABLE --
create index IDX_TCOV_BUILD_ID on TEST_COVERAGE(BUILD_ID);
create index IDX_TCOV_COMP_ID on TEST_COVERAGE(COMPONENT_ID);

-- USER_FILE TABLE --
create index IDX_UF_OWNER_ID on USER_FILE(OWNER_ID);

-- VERIFICATION_FAILURE_REASON TABLE --
create index IDX_VFR_VER_ID on VERIFICATION_FAILURE_REASON(VERIFICATION_ID);

-- VERIFICATION_TEST_RESULT_TYPES TABLE --
create index IDX_VTRT_VER_ID on VERIFICATION_TEST_RESULT_TYPES(VERIFICATION_ID);

-- WIDGET_SETTING TABLE --
create index IDX_WS_WIDGET_ID on WIDGET_SETTING(WIDGET_ID);

-- BUILD_VERIFICATION_CONF_LABELS TABLE --
create index IDX_BVCL_BVC_ID on BUILD_VERIFICATION_CONF_LABELS(BUILDVERIFICATIONCONF_ID);

-- BUILDGROUP_CUSTOM_PARAMETER TABLE --
create index IDX_BGCP_BG_ID on BUILDGROUP_CUSTOM_PARAMETER(BUILDGROUP_ID);

-- COMPONENT TABLE --
create index IDX_COMP_BG_ID on COMPONENT(BUILDGROUP_ID);

-- CUSTOM_VERIFICATION_CONF_FILE TABLE --
create index IDX_CVCF_CVC_ID on CUSTOM_VERIFICATION_CONF_FILE(CUSTOMVERIFICATIONCONFS_ID);
create index IDX_CVCF_CF_ID on CUSTOM_VERIFICATION_CONF_FILE(USERFILES_ID);

-- FILE_TRIGGER_PATTERN TABLE --
create index IDX_FTP_JOB_ID on FILE_TRIGGER_PATTERN(JOB_ID);

-- BUILDGROUP_CHANGE TABLE --
create index IDX_BGC_BUILDGROUPS_ID on BUILD_GROUP_CHANGE(BUILDGROUPS_ID);
create index IDX_BGC_CHANGES_ID on BUILD_GROUP_CHANGE(CHANGES_ID);

-- BUILD_INPUT_PARAM TABLE --
create index IDX_BIP_BUILDVER_ID on BUILD_INPUT_PARAM(BUILDVERIFICATIONCONF_ID);

-- BUILD_VERIFICATION_CONF TABLE --
create index IDX_BVC_BUILD_ID on BUILD_VERIFICATION_CONF(BUILD_ID);

-- CHANGE TABLE --
create index IDX_CHG_AUTHOR_EMAIL on CHANGE(AUTHOREMAIL);
create index IDX_CHG_PROJECT_ID on CHANGE(PROJECTID);

-- CISERVER TABLE --
create index IDX_CIS_SP_ID on CISERVER(SLAVEPOOL_ID);
create index IDX_CIS_UUID on CISERVER(UUID);

-- CHANGE_CHANGE TABLE --
create index IDX_CHG_CHG_PARENTCHANGES_ID on CHANGE_CHANGE(PARENTCHANGES_ID);
create index IDX_CHG_CHG_CHILDCHANGES_ID on CHANGE_CHANGE(CHILDCHANGES_ID);

-- CHANGE_FILE TABLE
create index IDX_CHANGE_FILE_CHANGE_ID on CHANGE_FILE(CHANGE_ID);

-- CHANGE_TRACKER TABLE --
create index IDX_CT_COMMIT_ID on CHANGE_TRACKER(COMMITID);

-- CUSTOM_PARAM TABLE --
create index IDX_CP_VERIFICATION_ID on CUSTOM_PARAM(VERIFICATION_ID);

-- CUSTOM_PARAM_VALUE TABLE --
create index IDX_CPV_CUSTOMPARAM_ID on CUSTOM_PARAM_VALUE(CUSTOMPARAM_ID);

-- CUSTOM_VERIFICATION_CONF TABLE --
create index IDX_CVC_JOBCUSTOMVER_ID on CUSTOM_VERIFICATION_CONF(JOBCUSTOMVERIFICATION_ID);
create index IDX_CVC_PRODUCT_ID on CUSTOM_VERIFICATION_CONF(PRODUCT_ID);

-- CUSTOM_VERIFICATION_PARAM TABLE --
create index IDX_CVP_CUSTOMVER_ID on CUSTOM_VERIFICATION_PARAM(CUSTOMVERIFICATION_ID);
create index IDX_CVP_CUSTOMPARAM_ID on CUSTOM_VERIFICATION_PARAM(CUSTOMPARAM_ID);

-- INPUT_PARAM TABLE --
create index IDX_IP_VERIFICATION_ID on INPUT_PARAM(VERIFICATION_ID);

-- JOB TABLE --
create index IDX_J_BRANCH_ID on JOB(BRANCH_ID);
create index IDX_J_OWNER_ID on JOB(OWNER_ID);
create index IDX_J_PROJECT_ID on JOB(PROJECTID);

-- JOB_CUSTOM_PARAMETER TABLE --
create index IDX_JCP_JOB_ID on JOB_CUSTOM_PARAMETER(JOB_ID);

-- JOB_ANNOUNCEMENT TABLE --
create index IDX_JA_JOB_ID on JOB_ANNOUNCEMENT(JOB_ID);

-- JOB_CUSTOM_VERIFICATION TABLE --
create index IDX_JCUV_JOB_ID on JOB_CUSTOM_VERIFICATION(JOB_ID);
create index IDX_JCUV_VERIFICATION_ID on JOB_CUSTOM_VERIFICATION(VERIFICATION_ID);

-- JOB_POST_VERIFICATION TABLE --
create index IDX_JPOV_JOB_ID on JOB_POST_VERIFICATION(JOB_ID);
create index IDX_JPOV_VERIFICATION_ID on JOB_POST_VERIFICATION(VERIFICATION_ID);

-- JOB_PRE_VERIFICATION TABLE --
create index IDX_JPREV_JOB_ID on JOB_PRE_VERIFICATION(JOB_ID);
create index IDX_JPREV_VERIFICATION_ID on JOB_PRE_VERIFICATION(VERIFICATION_ID);

-- JOB_VERIFICATION_CONF TABLE --
create index IDX_JVC_JOB_ID on JOB_VERIFICATION_CONF(JOB_ID);
create index IDX_JVC_VERIFICATION_ID on JOB_VERIFICATION_CONF(VERIFICATION_ID);
create index IDX_JVC_PRODUCT_ID on JOB_VERIFICATION_CONF(PRODUCT_ID);

-- JOB_VERIFICATION_CONF_FILE TABLE --
create index IDX_JVCF_JVC_ID on JOB_VERIFICATION_CONF_FILE(JOBVERIFICATIONCONFS_ID);
create index IDX_JVCF_UF_ID on JOB_VERIFICATION_CONF_FILE(USERFILES_ID);

-- MEM_CONSUMPTION TABLE --
create index IDX_MC_BUILD_ID on MEM_CONSUMPTION(BUILD_ID);
create index IDX_MC_COMP_ID on MEM_CONSUMPTION(COMPONENT_ID);

-- VERIFICATION TABLE --
create index IDX_V_UUID on VERIFICATION(UUID);

-- CISERVER TABLE --
create index IDX_CIS_UUID on CISERVER(UUID);

-- PRODUCT TABLE --
create index IDX_PROD_UUID on PRODUCT(UUID);

-- USER_FILE TABLE --
create index IDX_UF_UUID on USER_FILE(UUID);

-- PROJECT TABLE --
create index IDX_P_PROJECTGROUP_ID on PROJECT(PROJECTGROUP_ID);
create index IDX_P_GERRIT_ID on PROJECT(GERRIT_ID);

-- PROJECT_ANNOUNCEMENT TABLE --
create index IDX_PA_PROJECT_ID on PROJECT_ANNOUNCEMENT(PROJECT_ID);

-- PROJECT_CHANGE_TRACKER --
create index IDX_PCT_PROJECTS_ID on PROJECT_CHANGE_TRACKER(PROJECTS_ID);
create index IDX_PCT_CHANGETRACKERS_ID on PROJECT_CHANGE_TRACKER(CHANGETRACKERS_ID);

-- PROJECT_EXTERNAL_LINK TABLE --
create index IDX_PEL_PROJECT_ID on PROJECT_EXTERNAL_LINK(PROJECT_ID);

-- PROJECT_PRODUCT TABLE --
create index IDX_PP_PRODUCTS_ID on PROJECT_PRODUCT(PRODUCTS_ID);
create index IDX_PP_PROJECTS_ID on PROJECT_PRODUCT(PROJECTS_ID);

-- PROJECT_USER_ACCESS TABLE --
create index IDX_PUA_PROJECTACCESS_ID on PROJECT_USER_ACCESS(PROJECTACCESS_ID);
create index IDX_PUA_USERACCESS_ID on PROJECT_USER_ACCESS(USERACCESS_ID);

-- PROJECT_VERIFICATION TABLE --
create index IDX_PV_PROJECTS_ID on PROJECT_VERIFICATION(PROJECTS_ID);
create index IDX_PV_VERIFICATIONS_ID on PROJECT_VERIFICATION(VERIFICATIONS_ID);

-- PROJECT_VERIFICATION_CONF TABLE --
create index IDX_PVC_PROJECT_ID on PROJECT_VERIFICATION_CONF(PROJECT_ID);
create index IDX_PVC_VERIFICATION_ID on PROJECT_VERIFICATION_CONF(VERIFICATION_ID);
create index IDX_PVC_PRODUCT_ID on PROJECT_VERIFICATION_CONF(PRODUCT_ID);

-- REPORT_ACTION TABLE --
create index IDX_RA_JOB_ID on REPORT_ACTION(JOB_ID);

-- RESULT_DETAILS_PARAM TABLE --
create index IDX_RDP_VERIFICATION_ID on RESULT_DETAILS_PARAM(VERIFICATION_ID);

-- SLAVE_INSTANCE TABLE --
create index IDX_SI_SLAVEMACHINE_ID on SLAVE_INSTANCE(SLAVEMACHINE_ID);

-- SLAVE_INSTANCE_SLAVE_LABEL TABLE --
create index IDX_SISL_SLAVEINSTANCES_ID on SLAVE_INSTANCE_SLAVE_LABEL(SLAVEINSTANCES_ID);
create index IDX_SISL_SLAVELABELS_ID on SLAVE_INSTANCE_SLAVE_LABEL(SLAVELABELS_ID);

-- SLAVE_LABEL TABLE --
create index IDX_SL_NAME on SLAVE_LABEL(NAME);

-- SLAVE_POOL TABLE --
create index IDX_SP_NAME on SLAVE_POOL(NAME);

-- SLAVE_POOL_SLAVE_INSTANCE TABLE --
create index IDX_SPSI_SLAVEINSTANCES_ID on SLAVE_POOL_SLAVE_INSTANCE(SLAVEINSTANCES_ID);
create index IDX_SPSI_SLAVEPOOLS_ID on SLAVE_POOL_SLAVE_INSTANCE(SLAVEPOOLS_ID);

-- SYS_USER TABLE --
create index IDX_SU_LOGINNAME on SYS_USER(LOGINNAME);
create index IDX_SU_SECRETKEY on SYS_USER(SECRETKEY);

-- VERIFICATION_SLAVE_LABEL TABLE --
create index IDX_VSL_VERIFICATIONS_ID on VERIFICATION_SLAVE_LABEL(VERIFICATIONS_ID);
create index IDX_VSL_SLAVELABELS_ID on VERIFICATION_SLAVE_LABEL(SLAVELABELS_ID);

-- VERIFICATION_VERIFICATION TABLE --
create index IDX_VV_CHILDVERIFICATIONS_ID on VERIFICATION_VERIFICATION(CHILDVERIFICATIONS_ID);
create index IDX_VV_PARENTVERIFICATIONS_ID on VERIFICATION_VERIFICATION(PARENTVERIFICATIONS_ID);

-- SLAVE_STAT_PER_LABEL TABLE --
create index IDX_SSPL_PROVISIONTIME on SLAVE_STAT_PER_LABEL(PROVISIONTIME);
create index IDS_SSPL_SLAVELABEL_ID on SLAVE_STAT_PER_LABEL(SLAVELABEL_ID);
create index IDS_SSPL_SLAVEPOOL_ID on SLAVE_STAT_PER_LABEL(SLAVEPOOL_ID);

-- SLAVE_STAT_PER_MACHINE TABLE --
create index IDX_SSPM_PROVISIONTIME on SLAVE_STAT_PER_MACHINE(PROVISIONTIME);
create index IDX_SSPM_SLAVEMACHINE_ID on SLAVE_STAT_PER_MACHINE(SLAVEMACHINE_ID);
create index IDX_SSPM_SLAVEPOOL_ID on SLAVE_STAT_PER_MACHINE(SLAVEPOOL_ID);

-- SLAVE_STAT_PER_POOL TABLE --
create index IDX_SSPP_PROVISIONTIME on SLAVE_STAT_PER_POOL(PROVISIONTIME);
create index IDX_SSPP_SLAVEPOOL_ID on SLAVE_STAT_PER_POOL(SLAVEPOOL_ID);

-- STATUS_TRIGGER_PATTERN TABLE --
create index IDX_STP_JOB_ID on STATUS_TRIGGER_PATTERN(JOB_ID);

-- TEMPLATE_CUST_VER_CONF TABLE --
create index IDX_TCVC_CV_ID on TEMPLATE_CUST_VER_CONF(CUSTOMVERIFICATION_ID);
create index IDX_TCVC_PROD_ID on TEMPLATE_CUST_VER_CONF(PRODUCT_ID);

-- TEMPLATE_CUST_VER_PARAM TABLE --
create index IDX_TCVP_CP_ID on TEMPLATE_CUST_VER_PARAM(CUSTOMPARAM_ID);
create index IDX_TCVP_CV_ID on TEMPLATE_CUST_VER_PARAM(CUSTOMVERIFICATION_ID);

-- TEMPLATE_CUSTOM_VERIFICATION TABLE --
create index IDX_TCV_TEMPLATE_ID on TEMPLATE_CUSTOM_VERIFICATION(TEMPLATE_ID);
create index IDX_TCV_VERIFICATION_ID on TEMPLATE_CUSTOM_VERIFICATION(VERIFICATION_ID);

-- TEMPLATE_VERIFICATION_CONF TABLE --
create index IDX_TVC_PROD_ID on TEMPLATE_VERIFICATION_CONF(PRODUCT_ID);
create index IDX_TVC_TEMPLATE_ID on TEMPLATE_VERIFICATION_CONF(TEMPLATE_ID);
create index IDX_TVC_VERIFICATION_ID on TEMPLATE_VERIFICATION_CONF(VERIFICATION_ID);
